21+", start_date_time: "2019-02-03 20:00:00 -0500", end_date_time: "2019-02-03 22:00:00 -0500", location: "Where:The Green Briar Pub, 304 Washington St, Brighton, MA, 02135", cost: "FREE", website: "http://www.greenbriarpub.com/event-calendar/comedy-sundays-8-pm")

For over two years one of Boston's top underground comedy clubs takes over Somerville Brewing Company on Sunday nights for a dinner show. Come experience the Liquid Courage Comedy Club where we showcase Boston's top stand-up comedy acts, which have premiered in such capacities as The Last Comic Standing, Comedy Central, Netflix, MTV, Adult Swim, Conan, & mReservations are required for guaranteed seating, but walk-ins are welcome too. Doors open at 7PM. Guests that are dining with us are requested to arrive at 7PM. Guests that are joining us for the show without dinner will be charged a $5 cover. Show starts at 8:12PM. All guests must be 21+ Guests are able to order dinner and pints before, during, and afterIf you change plans and decide not to join us, we will be happy to reschedule, BUT you need to call the taproom at 800-428-1150 x6 to let them know to give your seats to another g", start_date_time: "2019-02-03 20:00:00 -0500", end_date_time: "2019-02-03 23:00:00 -0500", location: "Where:Somerville Brewing Company Brewery + Taproom, 15 Ward St, Somerville, MA, 02143", cost: "$5", website: "https://www.facebook.com/liquidcouragecomedy/?fb_dtsg_ag=AdyAGxJo-FFv6_Vsqd3deiUWcr4Zfy6HVRxRfCAJJMLgAg%3AAdyfGRtAsnZW1mCywQMYdANSt_jMN046f-UW2rqODNSZ_A")

Ever wondered what hilarious comedians from big fancy TV shows do the rest of the week? Sometimes they appear at your neighborhood bar! The funniest in New England and beyond can Even better, this is an open mic! You can see some newcomers among the cityâs best, all working out their kinks and developing their craft. If youâre interested in performing,http://www.midwaycafe.com/", start_date_time: "2019-02-03 21:00:00 -0500", end_date_time: "2019-02-03 23:59:00 -0500", location: "Where:Midway Cafe, 3496 Washington Street, Jamaica Plain, MA, 02130", cost: "FREE", website: "www.midwayorthehighway.com")

Event.create!(title: "McGreevy's FREE COMEDY: Every Monday & Tuesday", description: "Every Monday & Tuesday, McGreevy's has an incredible stand up comedy show. New lineup each shoHosted by Brian Higginbottom", start_date_time: "2019-02-04 20:00:00 -0500", end_date_time: "2019-02-04 21:30:00 -0500", location: "Where:McGreevy's Boston, 911 Boylston St., Boston, MA, 02115", cost: "FREE", website: "not found")

Event.create!(title: "The Mendoza Line Comedy Show", description: "Every Saturday, Zach Armentrout, Katie QuÃ©, and John Baglio bring the best comics from Boston and beyond to theAfter 8pm on the day of the show, tickets are available at the door until they sell out. If you have any questions, please contact us at mendozalinecomedy@gmail.com. Show is 21+.", start_date_time: "2019-02-09 21:00:00 -0500", end_date_time: "2019-02-09 23:00:00 -0500", location: "Where:Dugout Cafe, 722 Commonwealth Avenue, Boston, MA, 02215", cost: "$5", website: "https://www.eventbrite.com/e/the-mendoza-line-comedy-show-tickets-15228587114")

Fine citizens of Cambridge and the Boston/Somerville city areas, The 730 Tavern, Kitchen, and Patio is proud to present an on-the-floor hilarious evening of stand-up comedy at it'Come see comedians featured on Netflix, Network Television, and prestigious festivals. Eat, drink and bask in the warm glow of a hot audience. You'll be making hearty mouth soundsThe 730 is located just a few minutes away from the Central Square Subway stop on the redline, with cheap parking spots located off of Massachusetts Avenue. The fun begins around 2/6 The well Crafted Comedy lineup show! No real cheap thrills for this show, except for the usual cheap thrills that this show stands for. You'll love this lineup except for mayb2/20 It's no applause night! Laugh, cry, whistle, but no applause allowed! If a sound is emmited from the force of your hands coming together, then you are banned for life. Also w*Not only is this show free, every audience member that mentions this Boston Calender advertisement receives entitlement to 276 acres of South Dakota badlands. what a deal!", start_date_time: "2019-02-06 20:00:00 -0500", end_date_time: "2019-02-06 22:00:00 -0500", location: "Where:730 Tavern, Kitchen, and Patio, 730 Massachusetts Avenue,  Cambridge , MA, 02139", cost: "FREE", website: "https://www.eventbrite.com/myevent?eid=39574058073")

Event.create!(title: "Thunderbar Comedy Open Mic", description: "Thunderbar Comedy Open Mic is new material/no material each and every week. We want to hear all new jokes. Every. Single. Time. Check the facebook page for each week's theme or talk about anything at all.  Each week has a few fantastic features all worth checking out, so even if you're not doCome on down, have a few laughs and beers, do your new jokes, characters, crowdwork or answer questions from the audience! BUT IF YOU TRY OLD JOKES YOU WILL BE SHOT WITH A NERF DA", start_date_time: "2019-02-07 18:00:00 -0500", end_date_time: "2019-02-07 22:30:00 -0500", location: "Where:Thunderbar Comedy/Basement of Wonder Bar, 186 Harvard Ave, Allston, MA, 02134", cost: "FREE", website: "https://www.facebook.com/ThunderbarComedy/?ref=bookmarks&qsefr=1")

Event.create!(title: "Hideout Comedy at The White Bull Tavern! 7.30pm", description: "HIDEOUT COMEDY is back at a brand new location right around the corner, the WHITE BULL TAVERN! Located right in the heart of historic downtown Boston, come get a taste of the absolute BEST stand-up comics working today. These comedians are all pros, many having had their twitter and IG: @hideoutcomedy", start_date_time: "2019-02-08 19:30:00 -0500", end_date_time: "2019-02-08 21:30:00 -0500", location: "Where:The White Bull Tavern, 1 Union Street, Boston, MA, 02108", cost: "$10", website: "https://www.eventbrite.com/e/hideout-comedy-the-white-bull-friday-730pm-tickets-54826427320?aff=ebdssbdestsearch")

Event.create!(title: "Hideout Comedy at The White Bull Tavern! 7pm", description: "HIDEOUT COMEDY is back at a brand new location right around the corner, the WHITE BULL TAVERN! Located right in the heart of historic downtown Boston, come get a taste of the absolute BEST stand-up comics working today. These comedians are all pros, many having had their comtwitter and IG: @hideoutcomedy", start_date_time: "2019-02-09 19:00:00 -0500", end_date_time: "2019-02-09 21:00:00 -0500", location: "Where:The White Bull Tavern, 1 Union Street, Boston, MA, 02108", cost: "$10", website: "https://www.eventbrite.com/e/hideout-comedy-the-white-bull-saturday-700pm-tickets-54826353098?aff=ebdssbdestsearch")

Event.create!(title: "Comedy at Bill's Bar (Free! Wednesday, 7:30PM)", description: "Experience the best of Boston's stand-up comedy, next door to Fenway Park! Held every week on NOTE: The show sells out and tables fill up quickly. Seating is limited to the first 70 audience members. All additional ticket holders will be awarded standing room. Please buy your ticket in advance and arrive early (we'd recommend at least 30 minutes before showtime) to guarantee a table. And check out Eventbrite for more of our shows on Friday's & Saturday's!", start_date_time: "2019-02-06 19:30:00 -0500", end_date_time: "2019-02-06 21:00:00 -0500", location: "Where:Bill's Bar, 5 Lansdowne Street, Boston, MA, 02215", cost: "FREE", website: "https://billsbarweekdays.eventbrite.com/?aff=BillsBostonCalendar")

Event.create!(title: "Comedy at Bill's Bar ($10 Friday, 8PM)", description: "Experience the best of Boston's stand-up comedy, next door to Fenway Park! Held every week on the mainNOTE: The show sells out and tables fill up quickly. Seating is limited to the first 70 audience members. All additional ticket holders will be awarded standing room. Please buy your ticket in advance and arrive early (we'd recommend at least 30 minutes before showtime) to guarantee a table. And check out Eventbrite for more of our shows on Wednesday's & Saturday's!", start_date_time: "2019-02-08 20:00:00 -0500", end_date_time: "2019-02-08 21:30:00 -0500", location: "Where:Bill's Bar, 5 Lansdowne Street, Boston, MA, 02215", cost: "$10", website: "https://billsbarcomedy.eventbrite.com/?aff=BillsBostonCalendar")

Event.create!(title: "Comedy at Bill's Bar ($10 Saturday, 8PM)", description: "Experience the best of Boston's stand-up comedy, next door to Fenway Park! Held every week on the maNOTE: The show sells out and tables fill up quickly. Seating is limited to the first 70 audience members. All additional ticket holders will be awarded standing room. Please buy your ticket in advance and arrive early (we'd recommend at least 30 minutes before showtime) to guarantee a table. And check out Eventbrite for more of our shows on Wednesday's & Friday's!", start_date_time: "2019-02-09 20:00:00 -0500", end_date_time: "2019-02-09 21:30:00 -0500", location: "Where:Bill's Bar, 5 Lansdowne Street, Boston, MA, 02215", cost: "$10", website: "https://billsbarcomedy.eventbrite.com/?aff=BillsBostonCalendar")

One of Boston's oldest comedy houses, Nick's Comedy Stop has hosted such legendary comedians as Denis Leary, Jerry Seinfeld, Phyllis Diller, Lenny Clarke and Jay Leno for more than 30 years. As one of the top clubs in the country, Nick's draws national headliners while providing a space for up-and-coming talent, as well as the leading local stand-up comics in Boston, including Steve Sweeney and Joe Wong. This hub for humor -- named the Top Comedy Club in Boston by Travel + Leisure magazine -- is located in the heart of the city's Theater District.", start_date_time: "2019-02-08 20:00:00 -0500", end_date_time: "2019-02-08 22:00:00 -0500", location: "Where:Nick's Comedy Stop, 100 Warrenton St, Boston, MA, 02116", cost: "$20", website: "http://bit.ly/nicks-comedy-stop")

One of Boston's oldest comedy houses, Nick's Comedy Stop has hosted such legendary comedians as Denis Leary, Jerry Seinfeld, Phyllis Diller, Lenny Clarke and Jay Leno for more than 30 years. As one of the top clubs in the country, Nick's draws national headliners while providing a space for up-and-coming talent, as well as the leading local stand-up comics in Boston, including Steve Sweeney and Joe Wong. This hub for humor -- named the Top Comedy Club in Boston by Travel + Leisure magazine -- is located in the heart of the city's Theater District.", start_date_time: "2019-02-09 20:00:00 -0500", end_date_time: "2019-02-09 22:00:00 -0500", location: "Where:Nick's Comedy Stop, 100 Warrenton St, Boston, MA, 02116", cost: "$20", website: "http://bit.ly/nicks-comedy-stop")

➜  laughs git:(initial-config) ✗
